#[cfg(feature = "remote-tests")]
fn generate_conformance_tests() -> Result<(), Box<dyn std::error::Error>> {
    use std::fs;
    use std::path::Path;

    let test_dir = Path::new("conformance_tests/test_parsing");
    if !test_dir.exists() {
        return Ok(()); // Skip if tests don't exist yet
    }

    let mut should_pass_tests = String::new();
    let mut should_fail_tests = String::new();
    let mut impl_dependent_tests = String::new();

    for entry in fs::read_dir(test_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().unwrap_or_default() == "json" {
            let filename = path.file_name().unwrap().to_string_lossy();
            let test_name = sanitize_test_name(&filename);

            // Skip files that contain invalid UTF-8 (include_str! can't handle them)
            if fs::read_to_string(&path).is_err() {
                continue;
            }

            if filename.starts_with("y_") {
                should_pass_tests.push_str(&format!(
                    r#"    #[test]
    fn test_should_pass_{test_name}() {{
        let content = include_str!("../../conformance_tests/test_parsing/{filename}");
        let result = run_parser_test(content);
        assert!(result.is_ok(), "Test {filename} should pass but failed: {{:?}}", result.err());
    }}
"#,
                    test_name = test_name,
                    filename = filename
                ));
            } else if filename.starts_with("n_") {
                should_fail_tests.push_str(&format!(
                    r#"    #[test]
    fn test_should_fail_{test_name}() {{
        let content = include_str!("../../conformance_tests/test_parsing/{filename}");
        let result = run_parser_test(content);
        assert!(result.is_err(), "Test {filename} should fail but passed");
    }}
"#,
                    test_name = test_name,
                    filename = filename
                ));
            } else if filename.starts_with("i_") {
                impl_dependent_tests.push_str(&format!(
                    r#"    #[test]
    fn test_impl_dependent_{test_name}() {{
        let content = include_str!("../../conformance_tests/test_parsing/{filename}");
        let result = run_parser_test(content);
        // Implementation dependent - just run it, don't assert result
        println!("Test {filename}: {{:?}}", result);
    }}
"#,
                    test_name = test_name,
                    filename = filename
                ));
            }
        }
    }

    let generated_code = format!(
        r#"// Generated by build.rs - DO NOT EDIT
#[cfg(feature = "remote-tests")]
mod generated_conformance_tests {{
    use picojson::{{Event, ParseError, PullParser, SliceParser}};

    fn run_parser_test(json_content: &str) -> Result<usize, ParseError> {{
        let mut buffer = [0u8; 1024];
        let mut parser = SliceParser::with_buffer(json_content, &mut buffer);
        let mut event_count = 0;

        loop {{
            match parser.next_event() {{
                Ok(Event::EndDocument) => break,
                Ok(_event) => event_count += 1,
                Err(e) => return Err(e),
            }}
        }}
        Ok(event_count)
    }}

    mod should_pass {{
        use super::run_parser_test;
{should_pass_tests}
    }}

    mod should_fail {{
        use super::run_parser_test;
{should_fail_tests}
    }}

    mod impl_dependent {{
        use super::run_parser_test;
{impl_dependent_tests}
    }}
}}
"#,
        should_pass_tests = should_pass_tests,
        should_fail_tests = should_fail_tests,
        impl_dependent_tests = impl_dependent_tests
    );

    fs::write("tests/generated_conformance_tests.rs", generated_code)?;
    println!("cargo:warning=Generated conformance tests");

    Ok(())
}

fn sanitize_test_name(filename: &str) -> String {
    filename
        .replace(".json", "")
        .replace("-", "_")
        .replace("+", "_plus")
        .replace(".", "_dot")
        .replace("#", "_hash")
        .replace("(", "_lparen")
        .replace(")", "_rparen")
        .replace("[", "_lbracket")
        .replace("]", "_rbracket")
        .replace(" ", "_space")
        .replace(":", "_colon")
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Only download conformance tests if the remote-tests feature is enabled
    #[cfg(feature = "remote-tests")]
    {
        generate_conformance_tests()?;
        use std::fs;
        use std::io::{self, Read};
        use std::path::Path;
        let conformance_dir = Path::new("conformance_tests");

        // Skip download if conformance tests already exist
        if conformance_dir.exists() && conformance_dir.join("test_parsing").exists() {
            println!("cargo:warning=Conformance tests already exist, skipping download");
            return Ok(());
        }

        println!("cargo:warning=Downloading JSONTestSuite conformance tests...");

        let commit = "1ef36fa01286573e846ac449e8683f8833c5b26a";
        let url = format!("https://github.com/nst/JSONTestSuite/archive/{commit}.zip");

        println!("cargo:warning=Downloading from: {}", url);

        // Download the ZIP file
        let response = ureq::get(&url).call()?;
        let mut zip_bytes = Vec::new();
        response.into_reader().read_to_end(&mut zip_bytes)?;

        println!("cargo:warning=Downloaded {} bytes", zip_bytes.len());

        // Extract ZIP file
        let reader = std::io::Cursor::new(zip_bytes);
        let mut archive = zip::ZipArchive::new(reader)?;

        // Create output directory
        let output_dir = Path::new("conformance_tests");
        if !output_dir.exists() {
            fs::create_dir_all(output_dir)?;
        }

        println!("cargo:warning=Extracting {} files...", archive.len());

        for i in 0..archive.len() {
            let mut file = archive.by_index(i)?;
            let outpath = match file.enclosed_name() {
                Some(path) => {
                    // Strip the git hash directory prefix (JSONTestSuite-{hash}/)
                    let path_str = path.to_string_lossy();
                    if let Some(stripped) =
                        path_str.strip_prefix(&format!("JSONTestSuite-{}/", commit))
                    {
                        output_dir.join(stripped)
                    } else {
                        output_dir.join(path)
                    }
                }
                None => continue,
            };

            if file.name().ends_with('/') {
                // Directory
                fs::create_dir_all(&outpath)?;
            } else {
                // File
                if let Some(p) = outpath.parent() {
                    if !p.exists() {
                        fs::create_dir_all(p)?;
                    }
                }
                let mut outfile = fs::File::create(&outpath)?;
                io::copy(&mut file, &mut outfile)?;
            }

            if i % 500 == 0 {
                println!("cargo:warning=Extracted {} files...", i);
            }
        }

        println!(
            "cargo:warning=Extraction complete! Test files are in: {}",
            output_dir.display()
        );
        println!("cargo:warning=You can now run conformance tests with: cargo test --features remote-tests");
    }

    Ok(())
}
