[package]
name = "ujson"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", optional = true, features = ["derive"] }
log = "0.4.26"

[dev-dependencies]
env_logger = "0.11.3"
test-log = { version = "0.2.14", features = ["trace"] }

[features]
clap = ["dep:clap"]
